/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.umg.vistas;

import com.umg.controlador.ControladorCategoria;
import com.umg.controlador.ControladorGestionUsuarios;
import com.umg.controlador.ControladorPrecios;
import com.umg.modelo.ModeloCategoria;
import com.umg.modelo.ModeloGestionUsuarios;
import com.umg.modelo.ModeloPrecios;

/**
 *
 * @author axels
 */
public class VistaGestionUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form VistaCuentasPorCobrar
     */
    public VistaGestionUsuarios() {
        initComponents();
        ModeloGestionUsuarios modelo = new ModeloGestionUsuarios(this);
        ControladorGestionUsuarios controlador = new ControladorGestionUsuarios(modelo);
        setControlador(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cmbOrdenarPor = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCategorias = new javax.swing.JTable();
        btnLimpiar = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        lblLimpiar = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblNuevo = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblActualizar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblEliminar = new javax.swing.JLabel();
        btnBuscarEmpleado = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        lblBuscarCliente = new javax.swing.JLabel();
        cmbBuscarClientePor = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        txtBuscarCliente = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cmbEmpleado = new javax.swing.JComboBox<>();
        txtNITCliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cmbRol = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(880, 720));
        setPreferredSize(new java.awt.Dimension(880, 720));

        jPanel1.setBackground(new java.awt.Color(245, 247, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Skoda Pro", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(108, 117, 125));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestión de Usuarios");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 40));

        btnBuscar.setBackground(new java.awt.Color(245, 247, 250));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Buscar");
        btnBuscar.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        lblBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBoton1.png"))); // NOI18N
        btnBuscar.add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, -1, -1));

        txtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 220, 30));

        jLabel14.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(33, 37, 41));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Buscar");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 200, 20));

        cmbOrdenarPor.setBackground(new java.awt.Color(255, 255, 255));
        cmbOrdenarPor.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        cmbOrdenarPor.setForeground(new java.awt.Color(108, 117, 125));
        cmbOrdenarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código Usuario", "Usuario", "Rol", "Código Empleado", "Nombre Empleado" }));
        cmbOrdenarPor.setBorder(null);
        jPanel1.add(cmbOrdenarPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 200, 30));

        jLabel16.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(33, 37, 41));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Ordenar Por");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 200, 20));

        jLabel5.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(33, 37, 41));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Código Empleado");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 200, 20));

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 200, 30));

        jLabel6.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(33, 37, 41));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Usuario");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 200, 20));

        txtDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        txtDescripcion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 200, 30));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(660, 480));

        tblCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código Usuario", "Usuario", "Rol", "Código Empleado", "Nombre Empleado"
            }
        ));
        jScrollPane1.setViewportView(tblCategorias);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 600, 460));

        btnLimpiar.setBackground(new java.awt.Color(245, 247, 250));
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Limpiar");
        btnLimpiar.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        lblLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBoton1.png"))); // NOI18N
        btnLimpiar.add(lblLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 100, 30));

        btnNuevo.setBackground(new java.awt.Color(245, 247, 250));
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nuevo");
        btnNuevo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        lblNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBoton1.png"))); // NOI18N
        btnNuevo.add(lblNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        btnActualizar.setBackground(new java.awt.Color(245, 247, 250));
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Actualizar");
        btnActualizar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        lblActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBoton1.png"))); // NOI18N
        btnActualizar.add(lblActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, 30));

        btnEliminar.setBackground(new java.awt.Color(245, 247, 250));
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Eliminar");
        btnEliminar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        lblEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBoton1.png"))); // NOI18N
        btnEliminar.add(lblEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, -1, -1));

        btnBuscarEmpleado.setBackground(new java.awt.Color(245, 247, 250));
        btnBuscarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Buscar");
        btnBuscarEmpleado.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        lblBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBoton1.png"))); // NOI18N
        btnBuscarEmpleado.add(lblBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel1.add(btnBuscarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 30));

        cmbBuscarClientePor.setBackground(new java.awt.Color(255, 255, 255));
        cmbBuscarClientePor.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        cmbBuscarClientePor.setForeground(new java.awt.Color(108, 117, 125));
        cmbBuscarClientePor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Documento", "Nombre" }));
        cmbBuscarClientePor.setBorder(null);
        jPanel1.add(cmbBuscarClientePor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 200, 30));

        jLabel22.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(33, 37, 41));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Buscar Por");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 110, 20));

        txtBuscarCliente.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscarCliente.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel1.add(txtBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 200, 30));

        jLabel20.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(33, 37, 41));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Buscar Empleado");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 200, 20));

        jLabel21.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(33, 37, 41));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Empleado");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 200, 20));

        cmbEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        cmbEmpleado.setForeground(new java.awt.Color(108, 117, 125));
        cmbEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEmpleado.setBorder(null);
        jPanel1.add(cmbEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 200, 30));

        txtNITCliente.setEditable(false);
        txtNITCliente.setBackground(new java.awt.Color(255, 255, 255));
        txtNITCliente.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel1.add(txtNITCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 200, 30));

        jLabel10.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(33, 37, 41));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Código Empleado");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 200, 20));

        txtNombreCliente.setEditable(false);
        txtNombreCliente.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreCliente.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel1.add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 200, 30));

        jLabel11.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(33, 37, 41));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Documento Empleado");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 200, 20));

        cmbRol.setBackground(new java.awt.Color(255, 255, 255));
        cmbRol.setForeground(new java.awt.Color(108, 117, 125));
        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbRol.setBorder(null);
        jPanel1.add(cmbRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 200, 30));

        jLabel23.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(33, 37, 41));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Rol");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 200, 20));

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 200, 30));

        jLabel8.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(33, 37, 41));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Contraseña");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 200, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnActualizar;
    public javax.swing.JPanel btnBuscar;
    public javax.swing.JPanel btnBuscarEmpleado;
    public javax.swing.JPanel btnEliminar;
    public javax.swing.JPanel btnLimpiar;
    public javax.swing.JPanel btnNuevo;
    private javax.swing.JComboBox<String> cmbBuscarClientePor;
    public javax.swing.JComboBox<String> cmbEmpleado;
    private javax.swing.JComboBox<String> cmbOrdenarPor;
    public javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblActualizar;
    public javax.swing.JLabel lblBuscar;
    public javax.swing.JLabel lblBuscarCliente;
    public javax.swing.JLabel lblEliminar;
    public javax.swing.JLabel lblLimpiar;
    public javax.swing.JLabel lblNuevo;
    private javax.swing.JTable tblCategorias;
    public javax.swing.JTextField txtBuscar;
    public javax.swing.JTextField txtBuscarCliente;
    public javax.swing.JTextField txtCodigo;
    public javax.swing.JTextField txtDescripcion;
    public javax.swing.JTextField txtNITCliente;
    public javax.swing.JTextField txtNombreCliente;
    // End of variables declaration//GEN-END:variables
    public void setControlador(ControladorGestionUsuarios controlador) {
        this.btnActualizar.addMouseListener(controlador);
        this.btnEliminar.addMouseListener(controlador);
        this.btnNuevo.addMouseListener(controlador);
        this.btnBuscar.addMouseListener(controlador);
        this.btnLimpiar.addMouseListener(controlador);
    }
}
