/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.umg.vistas;

import com.umg.controlador.ControladorCompras;
import com.umg.controlador.ControladorProductos;
import com.umg.controlador.ControladorVentas;
import com.umg.modelo.ModeloCompras;
import com.umg.modelo.ModeloProducto;
import com.umg.modelo.ModeloVentas;

import javax.swing.*;

/**
 *
 * @author axels
 */
public class VistaCompras extends javax.swing.JPanel {

    /**
     * Creates new form VistaProductos
     */
    public VistaCompras() {
        initComponents();
        inicializarControlador();


    }
    private void inicializarControlador() {
        ModeloCompras modelo = new ModeloCompras(this);
        ControladorCompras controlador = new ControladorCompras(modelo);
        setControlador(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblAgregar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblEliminar = new javax.swing.JLabel();
        btnRegistrarCompra = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblRegistrarCompra = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtBanco = new javax.swing.JTextField();
        txtNumeroCuenta = new javax.swing.JTextField();
        txtNITProveedor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombreProveedor = new javax.swing.JTextField();
        lblPlazoCredito = new javax.swing.JLabel();
        txtPlazoCredito = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        lblTipoPlazo = new javax.swing.JLabel();
        cmbMetodoDePago = new javax.swing.JComboBox<>();
        cmbTipoPlazo = new javax.swing.JComboBox<>();
        cmbProveedor = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        txtInfoRepresentante = new javax.swing.JTextField();
        cmRepresentante = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        lblTipoPlazo1 = new javax.swing.JLabel();
        lblTipoPlazo2 = new javax.swing.JLabel();
        txtBuscarProducto = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnBuscarProducto = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lblBuscarProducto = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPrecioProducto = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtCantidadProducto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtStockDisponible = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtTotalCompra = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(880, 720));
        setPreferredSize(new java.awt.Dimension(880, 720));

        panelFondo.setBackground(new java.awt.Color(245, 247, 250));
        panelFondo.setMinimumSize(new java.awt.Dimension(880, 720));
        panelFondo.setPreferredSize(new java.awt.Dimension(880, 720));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Skoda Pro", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(108, 117, 125));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar Compra");
        panelFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 40));

        btnAgregar.setBackground(new java.awt.Color(245, 247, 250));
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Agregar");
        btnAgregar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        lblAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBoton1.png"))); // NOI18N
        btnAgregar.add(lblAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        panelFondo.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 100, 30));

        btnEliminar.setBackground(new java.awt.Color(245, 247, 250));
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Eliminar");
        btnEliminar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        lblEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBoton1.png"))); // NOI18N
        btnEliminar.add(lblEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        panelFondo.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 100, 30));

        btnRegistrarCompra.setBackground(new java.awt.Color(245, 247, 250));
        btnRegistrarCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarCompra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Reg. Compra");
        btnRegistrarCompra.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        lblRegistrarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBoton1.png"))); // NOI18N
        btnRegistrarCompra.add(lblRegistrarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        panelFondo.add(btnRegistrarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 640, 100, 30));

        jPanel2.setBackground(new java.awt.Color(245, 247, 250));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBanco.setBackground(new java.awt.Color(255, 255, 255));
        txtBanco.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel2.add(txtBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 200, 30));

        txtNumeroCuenta.setBackground(new java.awt.Color(255, 255, 255));
        txtNumeroCuenta.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel2.add(txtNumeroCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 200, 30));

        txtNITProveedor.setEditable(false);
        txtNITProveedor.setBackground(new java.awt.Color(255, 255, 255));
        txtNITProveedor.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel2.add(txtNITProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 200, 30));

        jLabel5.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(33, 37, 41));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("NIT Proveedor");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 200, 20));

        jLabel6.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(33, 37, 41));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Nombre Proveedor");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 200, 20));

        txtNombreProveedor.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreProveedor.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel2.add(txtNombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 200, 30));

        lblPlazoCredito.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        lblPlazoCredito.setForeground(new java.awt.Color(33, 37, 41));
        lblPlazoCredito.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPlazoCredito.setText("Plazo de Crédito");
        jPanel2.add(lblPlazoCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 200, 20));

        txtPlazoCredito.setBackground(new java.awt.Color(255, 255, 255));
        txtPlazoCredito.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel2.add(txtPlazoCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 200, 30));

        jLabel12.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(33, 37, 41));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Método de Pago");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 200, 20));

        lblTipoPlazo.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        lblTipoPlazo.setForeground(new java.awt.Color(33, 37, 41));
        lblTipoPlazo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTipoPlazo.setText("Banco");
        jPanel2.add(lblTipoPlazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 200, 20));

        cmbMetodoDePago.setBackground(new java.awt.Color(255, 255, 255));
        cmbMetodoDePago.setForeground(new java.awt.Color(108, 117, 125));
        cmbMetodoDePago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMetodoDePago.setBorder(null);
        jPanel2.add(cmbMetodoDePago, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 200, 30));

        cmbTipoPlazo.setBackground(new java.awt.Color(255, 255, 255));
        cmbTipoPlazo.setForeground(new java.awt.Color(108, 117, 125));
        cmbTipoPlazo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTipoPlazo.setBorder(null);
        jPanel2.add(cmbTipoPlazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 200, 30));

        cmbProveedor.setBackground(new java.awt.Color(255, 255, 255));
        cmbProveedor.setForeground(new java.awt.Color(108, 117, 125));
        cmbProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbProveedor.setBorder(null);
        jPanel2.add(cmbProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 200, 30));

        jLabel21.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(33, 37, 41));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Representante");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 200, 20));

        txtInfoRepresentante.setEditable(false);
        txtInfoRepresentante.setBackground(new java.awt.Color(255, 255, 255));
        txtInfoRepresentante.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel2.add(txtInfoRepresentante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 200, 30));

        cmRepresentante.setBackground(new java.awt.Color(255, 255, 255));
        cmRepresentante.setForeground(new java.awt.Color(108, 117, 125));
        cmRepresentante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmRepresentante.setBorder(null);
        jPanel2.add(cmRepresentante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 200, 30));

        jLabel22.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(33, 37, 41));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Proveedor");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 20));

        lblTipoPlazo1.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        lblTipoPlazo1.setForeground(new java.awt.Color(33, 37, 41));
        lblTipoPlazo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTipoPlazo1.setText("Tipo de Plazo");
        jPanel2.add(lblTipoPlazo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 200, 20));

        lblTipoPlazo2.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        lblTipoPlazo2.setForeground(new java.awt.Color(33, 37, 41));
        lblTipoPlazo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTipoPlazo2.setText("Numero de cuenta");
        jPanel2.add(lblTipoPlazo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 200, 20));

        panelFondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 230, 670));

        txtBuscarProducto.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscarProducto.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        panelFondo.add(txtBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 200, 30));

        jLabel14.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(33, 37, 41));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Buscar Producto");
        panelFondo.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 200, 20));

        btnBuscarProducto.setBackground(new java.awt.Color(245, 247, 250));
        btnBuscarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Buscar");
        btnBuscarProducto.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        lblBuscarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBoton1.png"))); // NOI18N
        btnBuscarProducto.add(lblBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        panelFondo.add(btnBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, 100, 30));

        txtNombreProducto.setEditable(false);
        txtNombreProducto.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreProducto.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        panelFondo.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 200, 30));

        jLabel8.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(33, 37, 41));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Nombre Producto");
        panelFondo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 160, 20));

        txtPrecioProducto.setEditable(false);
        txtPrecioProducto.setBackground(new java.awt.Color(255, 255, 255));
        txtPrecioProducto.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        panelFondo.add(txtPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 200, 30));

        jLabel17.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(33, 37, 41));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Precio");
        panelFondo.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 200, 20));

        txtCantidadProducto.setBackground(new java.awt.Color(255, 255, 255));
        txtCantidadProducto.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        panelFondo.add(txtCantidadProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 200, 30));

        jLabel10.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(33, 37, 41));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Cantidad");
        panelFondo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 200, 20));

        txtStockDisponible.setEditable(false);
        txtStockDisponible.setBackground(new java.awt.Color(255, 255, 255));
        txtStockDisponible.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        panelFondo.add(txtStockDisponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 170, 30));

        jLabel19.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(33, 37, 41));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Stock Disponible");
        panelFondo.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 170, 20));

        txtTotalCompra.setEditable(false);
        txtTotalCompra.setBackground(new java.awt.Color(255, 255, 255));
        txtTotalCompra.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        panelFondo.add(txtTotalCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 640, 200, 30));

        jLabel9.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(33, 37, 41));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Total");
        panelFondo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 620, 160, 20));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(660, 480));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblProductos);

        panelFondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 610, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnAgregar;
    public javax.swing.JPanel btnBuscarProducto;
    public javax.swing.JPanel btnEliminar;
    public javax.swing.JPanel btnRegistrarCompra;
    public javax.swing.JComboBox<String> cmRepresentante;
    public javax.swing.JComboBox<String> cmbMetodoDePago;
    public javax.swing.JComboBox<String> cmbProveedor;
    public javax.swing.JComboBox<String> cmbTipoPlazo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblAgregar;
    public javax.swing.JLabel lblBuscarProducto;
    public javax.swing.JLabel lblEliminar;
    public javax.swing.JLabel lblPlazoCredito;
    public javax.swing.JLabel lblRegistrarCompra;
    public javax.swing.JLabel lblTipoPlazo;
    public javax.swing.JLabel lblTipoPlazo1;
    public javax.swing.JLabel lblTipoPlazo2;
    private javax.swing.JPanel panelFondo;
    public javax.swing.JTable tblProductos;
    public javax.swing.JTextField txtBanco;
    public javax.swing.JTextField txtBuscarProducto;
    public javax.swing.JTextField txtCantidadProducto;
    public javax.swing.JTextField txtInfoRepresentante;
    public javax.swing.JTextField txtNITProveedor;
    public javax.swing.JTextField txtNombreProducto;
    public javax.swing.JTextField txtNombreProveedor;
    public javax.swing.JTextField txtNumeroCuenta;
    public javax.swing.JTextField txtPlazoCredito;
    public javax.swing.JTextField txtPrecioProducto;
    public javax.swing.JTextField txtStockDisponible;
    public javax.swing.JTextField txtTotalCompra;
    // End of variables declaration//GEN-END:variables

    public void setControlador (ControladorCompras controlador) {
        this.btnRegistrarCompra.addMouseListener(controlador);
        this.btnEliminar.addMouseListener(controlador);
        this.btnAgregar.addMouseListener(controlador);
        this.btnBuscarProducto.addMouseListener(controlador);
    }
    public javax.swing.JComboBox<String> getCmbMetodoDePago() {
        return cmbMetodoDePago;
    }

}
