/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.umg.vistas;

import com.umg.controlador.ControladorMenuConfiguracion;
import com.umg.modelo.ModeloMenuConfiguracion;

/**
 *
 * @author axels
 */
public class VistaMenuConfiguracion extends javax.swing.JPanel {

    /**
     * Creates new form VistaMenuCuentas
     */
    public VistaMenuConfiguracion() {
        initComponents();
        ModeloMenuConfiguracion modelo = new  ModeloMenuConfiguracion(this);
        ControladorMenuConfiguracion controlador = new ControladorMenuConfiguracion(modelo);
        setControlador(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        contenedor = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCategorias = new javax.swing.JPanel();
        lblIconoCategorias = new javax.swing.JLabel();
        lblCategorias = new javax.swing.JLabel();
        lblCategoriasSeleccionado = new javax.swing.JLabel();
        btnMarcas = new javax.swing.JPanel();
        lblIconoMarcas = new javax.swing.JLabel();
        lblMarcas = new javax.swing.JLabel();
        lblMarcasSeleccionado = new javax.swing.JLabel();
        btnMedidas = new javax.swing.JPanel();
        lblIconoMedidas = new javax.swing.JLabel();
        lblMedidas = new javax.swing.JLabel();
        lblMedidasSeleccionado = new javax.swing.JLabel();
        btnTipoDeCliente = new javax.swing.JPanel();
        lblIconoTipoDeCliente = new javax.swing.JLabel();
        lblTipoDeCliente = new javax.swing.JLabel();
        lblTipoDeClienteSeleccionado = new javax.swing.JLabel();
        btnTipoDeContacto = new javax.swing.JPanel();
        lblIconoTipoDeContacto = new javax.swing.JLabel();
        lblTipoDeContacto = new javax.swing.JLabel();
        lblTipoDeContactoSeleccionado = new javax.swing.JLabel();
        btnBancos = new javax.swing.JPanel();
        lblIconoBancos = new javax.swing.JLabel();
        lblBancos = new javax.swing.JLabel();
        lblBancosSeleccionado = new javax.swing.JLabel();
        btnMetodosDeLiquidacion = new javax.swing.JPanel();
        lblIconoMetodosDeLiquidacion = new javax.swing.JLabel();
        lblMetodosDeLiquidacion = new javax.swing.JLabel();
        lblMetodosDeLiquidacionSeleccionado = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1080, 720));

        panelFondo.setBackground(new java.awt.Color(245, 247, 250));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenedor.setBackground(new java.awt.Color(245, 247, 250));
        contenedor.setLayout(new java.awt.BorderLayout());
        panelFondo.add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 880, 720));

        panelMenu.setBackground(new java.awt.Color(245, 247, 250));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Skoda Pro", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(108, 117, 125));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Configuración");
        panelMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        btnCategorias.setBackground(new java.awt.Color(245, 247, 250));
        btnCategorias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCategorias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoInicio.png"))); // NOI18N
        btnCategorias.add(lblIconoCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblCategorias.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        lblCategorias.setForeground(new java.awt.Color(51, 51, 51));
        lblCategorias.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCategorias.setText("Categorías");
        btnCategorias.add(lblCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblCategoriasSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnCategorias.add(lblCategoriasSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 180, 40));

        btnMarcas.setBackground(new java.awt.Color(245, 247, 250));
        btnMarcas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMarcas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoMarcas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoClientes.png"))); // NOI18N
        btnMarcas.add(lblIconoMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblMarcas.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        lblMarcas.setForeground(new java.awt.Color(51, 51, 51));
        lblMarcas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMarcas.setText("Marcas");
        btnMarcas.add(lblMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblMarcasSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnMarcas.add(lblMarcasSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 180, 40));

        btnMedidas.setBackground(new java.awt.Color(245, 247, 250));
        btnMedidas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMedidas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoMedidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoVentas.png"))); // NOI18N
        btnMedidas.add(lblIconoMedidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblMedidas.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        lblMedidas.setForeground(new java.awt.Color(51, 51, 51));
        lblMedidas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMedidas.setText("Medidas");
        btnMedidas.add(lblMedidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblMedidasSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnMedidas.add(lblMedidasSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnMedidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 180, 40));

        btnTipoDeCliente.setBackground(new java.awt.Color(245, 247, 250));
        btnTipoDeCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTipoDeCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoTipoDeCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoProductos.png"))); // NOI18N
        btnTipoDeCliente.add(lblIconoTipoDeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblTipoDeCliente.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        lblTipoDeCliente.setForeground(new java.awt.Color(51, 51, 51));
        lblTipoDeCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTipoDeCliente.setText("Tipos de Cliente");
        btnTipoDeCliente.add(lblTipoDeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblTipoDeClienteSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnTipoDeCliente.add(lblTipoDeClienteSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnTipoDeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 180, 40));

        btnTipoDeContacto.setBackground(new java.awt.Color(245, 247, 250));
        btnTipoDeContacto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTipoDeContacto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoTipoDeContacto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoCompras.png"))); // NOI18N
        btnTipoDeContacto.add(lblIconoTipoDeContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblTipoDeContacto.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        lblTipoDeContacto.setForeground(new java.awt.Color(51, 51, 51));
        lblTipoDeContacto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTipoDeContacto.setText("Tipos de Contacto");
        btnTipoDeContacto.add(lblTipoDeContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblTipoDeContactoSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnTipoDeContacto.add(lblTipoDeContactoSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnTipoDeContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 180, 40));

        btnBancos.setBackground(new java.awt.Color(245, 247, 250));
        btnBancos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBancos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoBancos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoCuentasPorCoPa.png"))); // NOI18N
        btnBancos.add(lblIconoBancos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblBancos.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        lblBancos.setForeground(new java.awt.Color(51, 51, 51));
        lblBancos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBancos.setText("Bancos");
        btnBancos.add(lblBancos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblBancosSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnBancos.add(lblBancosSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnBancos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 180, 40));

        btnMetodosDeLiquidacion.setBackground(new java.awt.Color(245, 247, 250));
        btnMetodosDeLiquidacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMetodosDeLiquidacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoMetodosDeLiquidacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoUsuariosYRoles.png"))); // NOI18N
        btnMetodosDeLiquidacion.add(lblIconoMetodosDeLiquidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblMetodosDeLiquidacion.setFont(new java.awt.Font("Skoda Pro", 0, 12)); // NOI18N
        lblMetodosDeLiquidacion.setForeground(new java.awt.Color(51, 51, 51));
        lblMetodosDeLiquidacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMetodosDeLiquidacion.setText("Métodos de Liquidación");
        btnMetodosDeLiquidacion.add(lblMetodosDeLiquidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblMetodosDeLiquidacionSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnMetodosDeLiquidacion.add(lblMetodosDeLiquidacionSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnMetodosDeLiquidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 180, 40));

        panelFondo.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnBancos;
    public javax.swing.JPanel btnCategorias;
    public javax.swing.JPanel btnMarcas;
    public javax.swing.JPanel btnMedidas;
    public javax.swing.JPanel btnMetodosDeLiquidacion;
    public javax.swing.JPanel btnTipoDeCliente;
    public javax.swing.JPanel btnTipoDeContacto;
    public javax.swing.JPanel contenedor;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lblBancos;
    public javax.swing.JLabel lblBancosSeleccionado;
    public javax.swing.JLabel lblCategorias;
    public javax.swing.JLabel lblCategoriasSeleccionado;
    public javax.swing.JLabel lblIconoBancos;
    public javax.swing.JLabel lblIconoCategorias;
    public javax.swing.JLabel lblIconoMarcas;
    public javax.swing.JLabel lblIconoMedidas;
    public javax.swing.JLabel lblIconoMetodosDeLiquidacion;
    public javax.swing.JLabel lblIconoTipoDeCliente;
    public javax.swing.JLabel lblIconoTipoDeContacto;
    public javax.swing.JLabel lblMarcas;
    public javax.swing.JLabel lblMarcasSeleccionado;
    public javax.swing.JLabel lblMedidas;
    public javax.swing.JLabel lblMedidasSeleccionado;
    public javax.swing.JLabel lblMetodosDeLiquidacion;
    public javax.swing.JLabel lblMetodosDeLiquidacionSeleccionado;
    public javax.swing.JLabel lblTipoDeCliente;
    public javax.swing.JLabel lblTipoDeClienteSeleccionado;
    public javax.swing.JLabel lblTipoDeContacto;
    public javax.swing.JLabel lblTipoDeContactoSeleccionado;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables

    public void setControlador(ControladorMenuConfiguracion controlador) {
        this.btnCategorias.addMouseListener(controlador);
        this.btnMarcas.addMouseListener(controlador);
        this.btnMedidas.addMouseListener(controlador);
        this.btnTipoDeCliente.addMouseListener(controlador);
        this.btnTipoDeContacto.addMouseListener(controlador);
        this.btnBancos.addMouseListener(controlador);
        this.btnMetodosDeLiquidacion.addMouseListener(controlador);
    }
}
