/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.umg.vistas;

import com.umg.controlador.ControladorMenuCompras;
import com.umg.controlador.ControladorMenuConfiguracion;
import com.umg.controlador.ControladorMenuProductos;
import com.umg.controlador.ControladorMenuReportes;
import com.umg.modelo.ModeloMenuCompras;
import com.umg.modelo.ModeloMenuConfiguracion;
import com.umg.modelo.ModeloMenuProductos;
import com.umg.modelo.ModeloMenuReportes;

/**
 *
 * @author axels
 */
public class VistaMenuReportes extends javax.swing.JPanel {

    /**
     * Creates new form VistaMenuCuentas
     */
    public VistaMenuReportes() {
        initComponents();
        ModeloMenuReportes modelo = new  ModeloMenuReportes(this);
        ControladorMenuReportes controlador = new ControladorMenuReportes(modelo);
        setControlador(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        contenedor = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRepVentasYCompras = new javax.swing.JPanel();
        lblIconoRepVentasYCompras = new javax.swing.JLabel();
        lblRepVentasYCompras = new javax.swing.JLabel();
        lblRepVentasYComprasSeleccionado = new javax.swing.JLabel();
        btnRepClientesYProductos = new javax.swing.JPanel();
        lblIconoRepClientesYProductos = new javax.swing.JLabel();
        lblRepClientesYProductos = new javax.swing.JLabel();
        lblRepClientesYProductosSeleccionado = new javax.swing.JLabel();
        btnRepFinanzasEInventario = new javax.swing.JPanel();
        lblIconoRepFinanzasEInventario = new javax.swing.JLabel();
        lblRepFinanzasEInventario = new javax.swing.JLabel();
        lblRepFinanzasEInventarioSeleccionado = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1080, 720));

        panelFondo.setBackground(new java.awt.Color(245, 247, 250));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenedor.setBackground(new java.awt.Color(245, 247, 250));
        contenedor.setLayout(new java.awt.BorderLayout());
        panelFondo.add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 880, 720));

        panelMenu.setBackground(new java.awt.Color(245, 247, 250));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Skoda Pro", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(108, 117, 125));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reportes");
        panelMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        btnRepVentasYCompras.setBackground(new java.awt.Color(245, 247, 250));
        btnRepVentasYCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRepVentasYCompras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoRepVentasYCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoInicio.png"))); // NOI18N
        btnRepVentasYCompras.add(lblIconoRepVentasYCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblRepVentasYCompras.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        lblRepVentasYCompras.setForeground(new java.awt.Color(51, 51, 51));
        lblRepVentasYCompras.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRepVentasYCompras.setText("Ventas y Compras");
        btnRepVentasYCompras.add(lblRepVentasYCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblRepVentasYComprasSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnRepVentasYCompras.add(lblRepVentasYComprasSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnRepVentasYCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 180, 40));

        btnRepClientesYProductos.setBackground(new java.awt.Color(245, 247, 250));
        btnRepClientesYProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRepClientesYProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoRepClientesYProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoClientes.png"))); // NOI18N
        btnRepClientesYProductos.add(lblIconoRepClientesYProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblRepClientesYProductos.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        lblRepClientesYProductos.setForeground(new java.awt.Color(51, 51, 51));
        lblRepClientesYProductos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRepClientesYProductos.setText("Clientes y Productos");
        btnRepClientesYProductos.add(lblRepClientesYProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblRepClientesYProductosSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnRepClientesYProductos.add(lblRepClientesYProductosSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnRepClientesYProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 180, 40));

        btnRepFinanzasEInventario.setBackground(new java.awt.Color(245, 247, 250));
        btnRepFinanzasEInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRepFinanzasEInventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoRepFinanzasEInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoVentas.png"))); // NOI18N
        btnRepFinanzasEInventario.add(lblIconoRepFinanzasEInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblRepFinanzasEInventario.setFont(new java.awt.Font("Skoda Pro", 0, 13)); // NOI18N
        lblRepFinanzasEInventario.setForeground(new java.awt.Color(51, 51, 51));
        lblRepFinanzasEInventario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRepFinanzasEInventario.setText("Finanzas e Inventario");
        btnRepFinanzasEInventario.add(lblRepFinanzasEInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblRepFinanzasEInventarioSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnRepFinanzasEInventario.add(lblRepFinanzasEInventarioSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnRepFinanzasEInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 180, 40));

        panelFondo.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnRepClientesYProductos;
    public javax.swing.JPanel btnRepFinanzasEInventario;
    public javax.swing.JPanel btnRepVentasYCompras;
    public javax.swing.JPanel contenedor;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lblIconoRepClientesYProductos;
    public javax.swing.JLabel lblIconoRepFinanzasEInventario;
    public javax.swing.JLabel lblIconoRepVentasYCompras;
    public javax.swing.JLabel lblRepClientesYProductos;
    public javax.swing.JLabel lblRepClientesYProductosSeleccionado;
    public javax.swing.JLabel lblRepFinanzasEInventario;
    public javax.swing.JLabel lblRepFinanzasEInventarioSeleccionado;
    public javax.swing.JLabel lblRepVentasYCompras;
    public javax.swing.JLabel lblRepVentasYComprasSeleccionado;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables

    public void setControlador(ControladorMenuReportes controlador) {
        this.btnRepVentasYCompras.addMouseListener(controlador);
        this.btnRepClientesYProductos.addMouseListener(controlador);
        this.btnRepFinanzasEInventario.addMouseListener(controlador);
    }
}
