/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.umg.vistas;

import com.umg.controlador.ControladorMenuCompras;
import com.umg.controlador.ControladorMenuConfiguracion;
import com.umg.controlador.ControladorMenuProductos;
import com.umg.modelo.ModeloMenuCompras;
import com.umg.modelo.ModeloMenuConfiguracion;
import com.umg.modelo.ModeloMenuProductos;

/**
 *
 * @author axels
 */
public class VistaMenuCompras extends javax.swing.JPanel {

    /**
     * Creates new form VistaMenuCuentas
     */
    public VistaMenuCompras() {
        initComponents();
        ModeloMenuCompras modelo = new  ModeloMenuCompras(this);
        ControladorMenuCompras controlador = new ControladorMenuCompras(modelo);
        setControlador(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        contenedor = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRegistrarCompra = new javax.swing.JPanel();
        lblIconoRegistrarCompra = new javax.swing.JLabel();
        lblRegistrarCompra = new javax.swing.JLabel();
        lblRegistrarCompraSeleccionado = new javax.swing.JLabel();
        btnConsultaCompras = new javax.swing.JPanel();
        lblIconoConsultaCompras = new javax.swing.JLabel();
        lblConsultaCompras = new javax.swing.JLabel();
        lblConsultaComprasSeleccionado = new javax.swing.JLabel();
        btnProveedores = new javax.swing.JPanel();
        lblIconoProveedores = new javax.swing.JLabel();
        lblProveedores = new javax.swing.JLabel();
        lblProveedoresSeleccionado = new javax.swing.JLabel();
        btnCuentasPorPagar = new javax.swing.JPanel();
        lblIconoCuentasPorPagar = new javax.swing.JLabel();
        lblCuentasPorPagar = new javax.swing.JLabel();
        lblCuentasPorPagarSeleccionado = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1080, 720));

        panelFondo.setBackground(new java.awt.Color(245, 247, 250));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenedor.setBackground(new java.awt.Color(245, 247, 250));
        contenedor.setLayout(new java.awt.BorderLayout());
        panelFondo.add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 880, 720));

        panelMenu.setBackground(new java.awt.Color(245, 247, 250));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Skoda Pro", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(108, 117, 125));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Compras");
        panelMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        btnRegistrarCompra.setBackground(new java.awt.Color(245, 247, 250));
        btnRegistrarCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarCompra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoRegistrarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoInicio.png"))); // NOI18N
        btnRegistrarCompra.add(lblIconoRegistrarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblRegistrarCompra.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        lblRegistrarCompra.setForeground(new java.awt.Color(51, 51, 51));
        lblRegistrarCompra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRegistrarCompra.setText("Registrar Compra");
        btnRegistrarCompra.add(lblRegistrarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblRegistrarCompraSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnRegistrarCompra.add(lblRegistrarCompraSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnRegistrarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 180, 40));

        btnConsultaCompras.setBackground(new java.awt.Color(245, 247, 250));
        btnConsultaCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultaCompras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoConsultaCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoClientes.png"))); // NOI18N
        btnConsultaCompras.add(lblIconoConsultaCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblConsultaCompras.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        lblConsultaCompras.setForeground(new java.awt.Color(51, 51, 51));
        lblConsultaCompras.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblConsultaCompras.setText("Consulta Compras");
        btnConsultaCompras.add(lblConsultaCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblConsultaComprasSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnConsultaCompras.add(lblConsultaComprasSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnConsultaCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 180, 40));

        btnProveedores.setBackground(new java.awt.Color(245, 247, 250));
        btnProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProveedores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoVentas.png"))); // NOI18N
        btnProveedores.add(lblIconoProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblProveedores.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        lblProveedores.setForeground(new java.awt.Color(51, 51, 51));
        lblProveedores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblProveedores.setText("Proveedores");
        btnProveedores.add(lblProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblProveedoresSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnProveedores.add(lblProveedoresSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 180, 40));

        btnCuentasPorPagar.setBackground(new java.awt.Color(245, 247, 250));
        btnCuentasPorPagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCuentasPorPagar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoCuentasPorPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoProductos.png"))); // NOI18N
        btnCuentasPorPagar.add(lblIconoCuentasPorPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblCuentasPorPagar.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        lblCuentasPorPagar.setForeground(new java.awt.Color(51, 51, 51));
        lblCuentasPorPagar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCuentasPorPagar.setText("Cuentas por Pagar");
        btnCuentasPorPagar.add(lblCuentasPorPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblCuentasPorPagarSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnCuentasPorPagar.add(lblCuentasPorPagarSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnCuentasPorPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 180, 40));

        panelFondo.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnConsultaCompras;
    public javax.swing.JPanel btnCuentasPorPagar;
    public javax.swing.JPanel btnProveedores;
    public javax.swing.JPanel btnRegistrarCompra;
    public javax.swing.JPanel contenedor;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lblConsultaCompras;
    public javax.swing.JLabel lblConsultaComprasSeleccionado;
    public javax.swing.JLabel lblCuentasPorPagar;
    public javax.swing.JLabel lblCuentasPorPagarSeleccionado;
    public javax.swing.JLabel lblIconoConsultaCompras;
    public javax.swing.JLabel lblIconoCuentasPorPagar;
    public javax.swing.JLabel lblIconoProveedores;
    public javax.swing.JLabel lblIconoRegistrarCompra;
    public javax.swing.JLabel lblProveedores;
    public javax.swing.JLabel lblProveedoresSeleccionado;
    public javax.swing.JLabel lblRegistrarCompra;
    public javax.swing.JLabel lblRegistrarCompraSeleccionado;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables

    public void setControlador(ControladorMenuCompras controlador) {
        this.btnRegistrarCompra.addMouseListener(controlador);
        this.btnConsultaCompras.addMouseListener(controlador);
        this.btnProveedores.addMouseListener(controlador);
        this.btnCuentasPorPagar.addMouseListener(controlador);
    }
}
