/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.umg.vistas;

import com.umg.controlador.*;
import com.umg.modelo.*;

/**
 *
 * @author axels
 */
public class VistaMenuUsuariosYRoles extends javax.swing.JPanel {

    /**
     * Creates new form VistaMenuCuentas
     */
    public VistaMenuUsuariosYRoles() {
        initComponents();
        ModeloMenuUsuariosYRoles modelo = new  ModeloMenuUsuariosYRoles(this);
        ControladorMenuUsuariosYRoles controlador = new ControladorMenuUsuariosYRoles(modelo);
        setControlador(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        contenedor = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnGestionUsuarios = new javax.swing.JPanel();
        lblIconoGestionUsuarios = new javax.swing.JLabel();
        lblGestionUsuarios = new javax.swing.JLabel();
        lblGestionUsuariosSeleccionado = new javax.swing.JLabel();
        btnRoles = new javax.swing.JPanel();
        lblIconoRoles = new javax.swing.JLabel();
        lblRoles = new javax.swing.JLabel();
        lblRolesSeleccionado = new javax.swing.JLabel();
        btnAsignacionAcceso = new javax.swing.JPanel();
        lblIconoAsignacionAcceso = new javax.swing.JLabel();
        lblAsignacionAcceso = new javax.swing.JLabel();
        lblAsignacionAccesoSeleccionado = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1080, 720));

        panelFondo.setBackground(new java.awt.Color(245, 247, 250));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenedor.setBackground(new java.awt.Color(245, 247, 250));
        contenedor.setLayout(new java.awt.BorderLayout());
        panelFondo.add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 880, 720));

        panelMenu.setBackground(new java.awt.Color(245, 247, 250));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Skoda Pro", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(108, 117, 125));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Usuarios y Roles");
        panelMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        btnGestionUsuarios.setBackground(new java.awt.Color(245, 247, 250));
        btnGestionUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGestionUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoGestionUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoInicio.png"))); // NOI18N
        btnGestionUsuarios.add(lblIconoGestionUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblGestionUsuarios.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        lblGestionUsuarios.setForeground(new java.awt.Color(51, 51, 51));
        lblGestionUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGestionUsuarios.setText("Gestión de Usuarios");
        btnGestionUsuarios.add(lblGestionUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblGestionUsuariosSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnGestionUsuarios.add(lblGestionUsuariosSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnGestionUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 180, 40));

        btnRoles.setBackground(new java.awt.Color(245, 247, 250));
        btnRoles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRoles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoRoles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoClientes.png"))); // NOI18N
        btnRoles.add(lblIconoRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblRoles.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        lblRoles.setForeground(new java.awt.Color(51, 51, 51));
        lblRoles.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRoles.setText("Roles");
        btnRoles.add(lblRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblRolesSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnRoles.add(lblRolesSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 180, 40));

        btnAsignacionAcceso.setBackground(new java.awt.Color(245, 247, 250));
        btnAsignacionAcceso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAsignacionAcceso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoAsignacionAcceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoVentas.png"))); // NOI18N
        btnAsignacionAcceso.add(lblIconoAsignacionAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblAsignacionAcceso.setFont(new java.awt.Font("Skoda Pro", 0, 13)); // NOI18N
        lblAsignacionAcceso.setForeground(new java.awt.Color(51, 51, 51));
        lblAsignacionAcceso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAsignacionAcceso.setText("Asignación de Accesos");
        btnAsignacionAcceso.add(lblAsignacionAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblAsignacionAccesoSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnAsignacionAcceso.add(lblAsignacionAccesoSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnAsignacionAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 180, 40));

        panelFondo.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnAsignacionAcceso;
    public javax.swing.JPanel btnGestionUsuarios;
    public javax.swing.JPanel btnRoles;
    public javax.swing.JPanel contenedor;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lblAsignacionAcceso;
    public javax.swing.JLabel lblAsignacionAccesoSeleccionado;
    public javax.swing.JLabel lblGestionUsuarios;
    public javax.swing.JLabel lblGestionUsuariosSeleccionado;
    public javax.swing.JLabel lblIconoAsignacionAcceso;
    public javax.swing.JLabel lblIconoGestionUsuarios;
    public javax.swing.JLabel lblIconoRoles;
    public javax.swing.JLabel lblRoles;
    public javax.swing.JLabel lblRolesSeleccionado;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables

    public void setControlador(ControladorMenuUsuariosYRoles controlador) {
        this.btnGestionUsuarios.addMouseListener(controlador);
        this.btnRoles.addMouseListener(controlador);
        this.btnAsignacionAcceso.addMouseListener(controlador);
    }
}
