/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.umg.vistas;

import com.umg.controlador.ControladorEmpleados;
import com.umg.modelo.ModeloEmpleados;

import javax.swing.*;

/**
 *
 * @author axels
 */
public class VistaEmpleados extends javax.swing.JPanel {

    /**
     * Creates new form VistaProductos
     */
    public VistaEmpleados() {
        initComponents();
        inicializarControlador();


    }
    private void inicializarControlador() {
        ModeloEmpleados modelo = new ModeloEmpleados(this);
        ControladorEmpleados controlador = new ControladorEmpleados(modelo);
        setControlador(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        btnNuevo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblNuevo = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblEliminar = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblActualizar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtCodigoEmpleado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDpi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPrimerNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txxSegundoApellido = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtApellidoCasada = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cmbMedida = new javax.swing.JComboBox<>();
        txtSegundoNombre = new javax.swing.JTextField();
        txtStockMinimo1 = new javax.swing.JTextField();
        txtBuscar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lblBuscar = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cmbOrdenarPor = new javax.swing.JComboBox<>();
        btnLimpiar = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        lblLimpiar = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1080, 720));

        panelFondo.setBackground(new java.awt.Color(245, 247, 250));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Skoda Pro", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(108, 117, 125));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Empleados");
        panelFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 40));

        panelTabla.setBackground(new java.awt.Color(245, 247, 250));
        panelTabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(660, 480));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProductos);

        panelTabla.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 530));

        panelFondo.add(panelTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 580, 530));

        btnNuevo.setBackground(new java.awt.Color(245, 247, 250));
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nuevo");
        btnNuevo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        lblNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBoton1.png"))); // NOI18N
        btnNuevo.add(lblNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        panelFondo.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 630, 100, 30));

        btnEliminar.setBackground(new java.awt.Color(245, 247, 250));
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Eliminar");
        btnEliminar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        lblEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBoton1.png"))); // NOI18N
        btnEliminar.add(lblEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        panelFondo.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 630, 100, 30));

        btnActualizar.setBackground(new java.awt.Color(245, 247, 250));
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Actualizar");
        btnActualizar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        lblActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBoton1.png"))); // NOI18N
        btnActualizar.add(lblActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        panelFondo.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 670, 100, 30));

        jPanel2.setBackground(new java.awt.Color(245, 247, 250));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCodigoEmpleado.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel2.add(txtCodigoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 200, 30));

        jLabel5.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(33, 37, 41));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Codigo Empleado");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 200, 20));

        jLabel6.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(33, 37, 41));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Documento Identificación");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 200, 20));

        txtDpi.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel2.add(txtDpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 200, 30));

        jLabel7.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(33, 37, 41));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Primer Nombre");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 200, 20));

        txtPrimerNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel2.add(txtPrimerNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 200, 30));

        jLabel8.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(33, 37, 41));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Segundo Nombre");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 160, 20));

        txxSegundoApellido.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel2.add(txxSegundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 200, 30));

        jLabel10.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(33, 37, 41));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Nombre Jefe");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 200, 20));

        txtApellidoCasada.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel2.add(txtApellidoCasada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 200, 30));

        jLabel11.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(33, 37, 41));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Apellido De Casada");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 200, 20));

        jLabel12.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(33, 37, 41));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Primer Apellido");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 200, 20));

        jLabel13.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(33, 37, 41));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Segundo Apellido");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 200, 20));

        cmbMedida.setForeground(new java.awt.Color(108, 117, 125));
        cmbMedida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMedida.setBorder(null);
        jPanel2.add(cmbMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 200, 30));

        txtSegundoNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel2.add(txtSegundoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 200, 30));

        txtStockMinimo1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel2.add(txtStockMinimo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 200, 30));

        panelFondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 360, 560));

        txtBuscar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        panelFondo.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 340, 30));

        jLabel14.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(33, 37, 41));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Buscar");
        panelFondo.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 200, 20));

        btnBuscar.setBackground(new java.awt.Color(245, 247, 250));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Buscar");
        btnBuscar.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        lblBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBoton1.png"))); // NOI18N
        btnBuscar.add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        panelFondo.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 100, 30));

        jLabel16.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(33, 37, 41));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Ordenar Por");
        panelFondo.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 200, 20));

        cmbOrdenarPor.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        cmbOrdenarPor.setForeground(new java.awt.Color(108, 117, 125));
        cmbOrdenarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo", "Nombre", "Categoría", "Stock", "Precio" }));
        cmbOrdenarPor.setBorder(null);
        panelFondo.add(cmbOrdenarPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 110, 30));

        btnLimpiar.setBackground(new java.awt.Color(245, 247, 250));
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Limpiar");
        btnLimpiar.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        lblLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBoton1.png"))); // NOI18N
        btnLimpiar.add(lblLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        panelFondo.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 670, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnActualizar;
    public javax.swing.JPanel btnBuscar;
    public javax.swing.JPanel btnEliminar;
    public javax.swing.JPanel btnLimpiar;
    public javax.swing.JPanel btnNuevo;
    public javax.swing.JComboBox<String> cmbMedida;
    private javax.swing.JComboBox<String> cmbOrdenarPor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblActualizar;
    public javax.swing.JLabel lblBuscar;
    public javax.swing.JLabel lblEliminar;
    public javax.swing.JLabel lblLimpiar;
    public javax.swing.JLabel lblNuevo;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JTable tblProductos;
    public javax.swing.JTextField txtApellidoCasada;
    public javax.swing.JTextField txtBuscar;
    public javax.swing.JTextField txtCodigoEmpleado;
    public javax.swing.JTextField txtDpi;
    public javax.swing.JTextField txtPrimerNombre;
    public javax.swing.JTextField txtSegundoNombre;
    public javax.swing.JTextField txtStockMinimo1;
    public javax.swing.JTextField txxSegundoApellido;
    // End of variables declaration//GEN-END:variables

    public void setControlador (ControladorEmpleados controlador) {
        this.btnActualizar.addMouseListener(controlador);
        this.btnEliminar.addMouseListener(controlador);
        this.btnNuevo.addMouseListener(controlador);
        this.btnBuscar.addMouseListener(controlador);
        this.btnLimpiar.addMouseListener(controlador);
    }
}
