/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.umg.vistas;

import com.umg.controlador.ControladorMenuCuentas;
import com.umg.modelo.ModeloMenuCuentas;

/**
 *
 * @author axels
 */
public class VistaMenuCuentas extends javax.swing.JPanel {

    /**
     * Creates new form VistaMenuCuentas
     */
    public VistaMenuCuentas() {
        initComponents();
        ModeloMenuCuentas modelo = new ModeloMenuCuentas(this);
        ControladorMenuCuentas controlador = new ControladorMenuCuentas(modelo);
        setControlador(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCuentasPorCobrar = new javax.swing.JPanel();
        lblIconoCuentasPorCobrar = new javax.swing.JLabel();
        lblCuentasPorCobrar = new javax.swing.JLabel();
        lblCuentasPorCobrarSeleccionado = new javax.swing.JLabel();
        btnCuentasPorPagar = new javax.swing.JPanel();
        lblIconCuentasPorPagar = new javax.swing.JLabel();
        lblCuentasPorPagar = new javax.swing.JLabel();
        lblCuentasPorPagarSeleccionado = new javax.swing.JLabel();
        contenedor = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1080, 720));

        panelFondo.setBackground(new java.awt.Color(245, 247, 250));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenu.setBackground(new java.awt.Color(245, 247, 250));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Skoda Pro", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(108, 117, 125));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cuentas");
        panelMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        btnCuentasPorCobrar.setBackground(new java.awt.Color(245, 247, 250));
        btnCuentasPorCobrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCuentasPorCobrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoCuentasPorCobrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoInicio.png"))); // NOI18N
        btnCuentasPorCobrar.add(lblIconoCuentasPorCobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblCuentasPorCobrar.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        lblCuentasPorCobrar.setForeground(new java.awt.Color(51, 51, 51));
        lblCuentasPorCobrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCuentasPorCobrar.setText("Cuentas por Cobrar");
        btnCuentasPorCobrar.add(lblCuentasPorCobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblCuentasPorCobrarSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnCuentasPorCobrar.add(lblCuentasPorCobrarSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnCuentasPorCobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 180, 40));

        btnCuentasPorPagar.setBackground(new java.awt.Color(245, 247, 250));
        btnCuentasPorPagar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCuentasPorPagar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconCuentasPorPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoClientes.png"))); // NOI18N
        btnCuentasPorPagar.add(lblIconCuentasPorPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblCuentasPorPagar.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        lblCuentasPorPagar.setForeground(new java.awt.Color(51, 51, 51));
        lblCuentasPorPagar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCuentasPorPagar.setText("Cuentas por Pagar");
        btnCuentasPorPagar.add(lblCuentasPorPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblCuentasPorPagarSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnCuentasPorPagar.add(lblCuentasPorPagarSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnCuentasPorPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 180, 40));

        panelFondo.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 720));

        contenedor.setBackground(new java.awt.Color(245, 247, 250));
        contenedor.setLayout(new java.awt.BorderLayout());
        panelFondo.add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 880, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnCuentasPorCobrar;
    public javax.swing.JPanel btnCuentasPorPagar;
    public javax.swing.JPanel contenedor;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lblCuentasPorCobrar;
    public javax.swing.JLabel lblCuentasPorCobrarSeleccionado;
    public javax.swing.JLabel lblCuentasPorPagar;
    public javax.swing.JLabel lblCuentasPorPagarSeleccionado;
    public javax.swing.JLabel lblIconCuentasPorPagar;
    public javax.swing.JLabel lblIconoCuentasPorCobrar;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables

    public void setControlador(ControladorMenuCuentas controlador) {
        this.btnCuentasPorCobrar.addMouseListener(controlador);
        this.btnCuentasPorPagar.addMouseListener(controlador);

    }
}
