/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.umg.vistas;

/**
 *
 * @author axels
 */
public class VistaMenuConfiguracion extends javax.swing.JPanel {

    /**
     * Creates new form VistaMenuCuentas
     */
    public VistaMenuConfiguracion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        contenedor = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnInicio = new javax.swing.JPanel();
        lblIconoInicio = new javax.swing.JLabel();
        lblInicio = new javax.swing.JLabel();
        lblInicioSeleccionado = new javax.swing.JLabel();
        btnClientes = new javax.swing.JPanel();
        lblIconClientes = new javax.swing.JLabel();
        lblClientes = new javax.swing.JLabel();
        lblClientesSeleccionado = new javax.swing.JLabel();
        btnVentas = new javax.swing.JPanel();
        lblIconoVentas = new javax.swing.JLabel();
        lblVentas = new javax.swing.JLabel();
        lblVentasSeleccionado = new javax.swing.JLabel();
        btnProductos = new javax.swing.JPanel();
        lblIconoProductos = new javax.swing.JLabel();
        lblProductos = new javax.swing.JLabel();
        lblProductosSeleccionado = new javax.swing.JLabel();
        btnCompras = new javax.swing.JPanel();
        lblIconoCompras = new javax.swing.JLabel();
        lblCompras = new javax.swing.JLabel();
        lblComprasSeleccionado = new javax.swing.JLabel();
        btnCuentasPorCoPa = new javax.swing.JPanel();
        lblIconoCuentasPorCoPa = new javax.swing.JLabel();
        lblCuentasPorCoPa = new javax.swing.JLabel();
        lblCuentasPorCoPaSeleccionado = new javax.swing.JLabel();
        btnUsuariosYRoles = new javax.swing.JPanel();
        lblIconoUsuarioYRoles = new javax.swing.JLabel();
        lblUsuariosYRoles = new javax.swing.JLabel();
        lblUsuariosYRolesSeleccionado = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1080, 720));

        panelFondo.setBackground(new java.awt.Color(245, 247, 250));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenedor.setLayout(new java.awt.BorderLayout());
        panelFondo.add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 880, 720));

        panelMenu.setBackground(new java.awt.Color(245, 247, 250));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Skoda Pro", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(108, 117, 125));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Configuración");
        panelMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        btnInicio.setBackground(new java.awt.Color(245, 247, 250));
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoInicio.png"))); // NOI18N
        btnInicio.add(lblIconoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblInicio.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        lblInicio.setForeground(new java.awt.Color(51, 51, 51));
        lblInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblInicio.setText("Categorías");
        btnInicio.add(lblInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblInicioSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnInicio.add(lblInicioSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 180, 40));

        btnClientes.setBackground(new java.awt.Color(245, 247, 250));
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoClientes.png"))); // NOI18N
        btnClientes.add(lblIconClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblClientes.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        lblClientes.setForeground(new java.awt.Color(51, 51, 51));
        lblClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblClientes.setText("Marcas");
        btnClientes.add(lblClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblClientesSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnClientes.add(lblClientesSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 180, 40));

        btnVentas.setBackground(new java.awt.Color(245, 247, 250));
        btnVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoVentas.png"))); // NOI18N
        btnVentas.add(lblIconoVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblVentas.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        lblVentas.setForeground(new java.awt.Color(51, 51, 51));
        lblVentas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblVentas.setText("Medidas");
        btnVentas.add(lblVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblVentasSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnVentas.add(lblVentasSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 180, 40));

        btnProductos.setBackground(new java.awt.Color(245, 247, 250));
        btnProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoProductos.png"))); // NOI18N
        btnProductos.add(lblIconoProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblProductos.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        lblProductos.setForeground(new java.awt.Color(51, 51, 51));
        lblProductos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblProductos.setText("Tipos de Cliente");
        btnProductos.add(lblProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblProductosSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnProductos.add(lblProductosSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 180, 40));

        btnCompras.setBackground(new java.awt.Color(245, 247, 250));
        btnCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCompras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoCompras.png"))); // NOI18N
        btnCompras.add(lblIconoCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblCompras.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        lblCompras.setForeground(new java.awt.Color(51, 51, 51));
        lblCompras.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCompras.setText("Tipos de Contacto");
        btnCompras.add(lblCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblComprasSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnCompras.add(lblComprasSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 180, 40));

        btnCuentasPorCoPa.setBackground(new java.awt.Color(245, 247, 250));
        btnCuentasPorCoPa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCuentasPorCoPa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoCuentasPorCoPa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoCuentasPorCoPa.png"))); // NOI18N
        btnCuentasPorCoPa.add(lblIconoCuentasPorCoPa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblCuentasPorCoPa.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        lblCuentasPorCoPa.setForeground(new java.awt.Color(51, 51, 51));
        lblCuentasPorCoPa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCuentasPorCoPa.setText("Bancos");
        btnCuentasPorCoPa.add(lblCuentasPorCoPa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblCuentasPorCoPaSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnCuentasPorCoPa.add(lblCuentasPorCoPaSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnCuentasPorCoPa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 180, 40));

        btnUsuariosYRoles.setBackground(new java.awt.Color(245, 247, 250));
        btnUsuariosYRoles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuariosYRoles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoUsuarioYRoles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoUsuariosYRoles.png"))); // NOI18N
        btnUsuariosYRoles.add(lblIconoUsuarioYRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblUsuariosYRoles.setFont(new java.awt.Font("Skoda Pro", 0, 12)); // NOI18N
        lblUsuariosYRoles.setForeground(new java.awt.Color(51, 51, 51));
        lblUsuariosYRoles.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsuariosYRoles.setText("Métodos de Liquidación");
        btnUsuariosYRoles.add(lblUsuariosYRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblUsuariosYRolesSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnUsuariosYRoles.add(lblUsuariosYRolesSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnUsuariosYRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 180, 40));

        panelFondo.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnClientes;
    public javax.swing.JPanel btnCompras;
    public javax.swing.JPanel btnCuentasPorCoPa;
    public javax.swing.JPanel btnInicio;
    public javax.swing.JPanel btnProductos;
    public javax.swing.JPanel btnUsuariosYRoles;
    public javax.swing.JPanel btnVentas;
    public javax.swing.JPanel contenedor;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lblClientes;
    public javax.swing.JLabel lblClientesSeleccionado;
    public javax.swing.JLabel lblCompras;
    public javax.swing.JLabel lblComprasSeleccionado;
    public javax.swing.JLabel lblCuentasPorCoPa;
    public javax.swing.JLabel lblCuentasPorCoPaSeleccionado;
    public javax.swing.JLabel lblIconClientes;
    public javax.swing.JLabel lblIconoCompras;
    public javax.swing.JLabel lblIconoCuentasPorCoPa;
    public javax.swing.JLabel lblIconoInicio;
    public javax.swing.JLabel lblIconoProductos;
    public javax.swing.JLabel lblIconoUsuarioYRoles;
    public javax.swing.JLabel lblIconoVentas;
    public javax.swing.JLabel lblInicio;
    public javax.swing.JLabel lblInicioSeleccionado;
    public javax.swing.JLabel lblProductos;
    public javax.swing.JLabel lblProductosSeleccionado;
    public javax.swing.JLabel lblUsuariosYRoles;
    public javax.swing.JLabel lblUsuariosYRolesSeleccionado;
    public javax.swing.JLabel lblVentas;
    public javax.swing.JLabel lblVentasSeleccionado;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
