 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.umg.vistas;
import com.umg.controlador.ControladorClientes;
import com.umg.controlador.ControladorMovimientoCuentas;
import com.umg.modelo.ModeloMovimientoCuentas;

/**
 *
 * @author axels
 */
public class VistaMovimientoCuentas extends javax.swing.JPanel {

    /**
     * Creates new form VistaClientes
     */
    public VistaMovimientoCuentas() {
        initComponents();
        ModeloMovimientoCuentas modelo = new ModeloMovimientoCuentas(this);
        ControladorMovimientoCuentas controlador = new ControladorMovimientoCuentas(modelo);
        setControlador(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panelTabla = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lblBuscar = new javax.swing.JLabel();
        cmbOrdenarPor = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClientes1 = new javax.swing.JTable();
        cmbOrdenarPor1 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMovCuentas = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtBuscar1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtBuscar2 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtBuscar3 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtBuscar4 = new javax.swing.JTextField();
        txtBuscar5 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(880, 720));
        setPreferredSize(new java.awt.Dimension(880, 720));

        panelFondo.setBackground(new java.awt.Color(245, 247, 250));
        panelFondo.setMinimumSize(new java.awt.Dimension(880, 720));
        panelFondo.setPreferredSize(new java.awt.Dimension(880, 720));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Skoda Pro", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(108, 117, 125));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Movimiento de Cuentas");
        panelFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 40));

        jPanel2.setBackground(new java.awt.Color(245, 247, 250));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTabla.setBackground(new java.awt.Color(245, 247, 250));
        panelTabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(panelTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 610, -1));

        btnBuscar.setBackground(new java.awt.Color(245, 247, 250));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Buscar");
        btnBuscar.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        lblBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBoton1.png"))); // NOI18N
        btnBuscar.add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        cmbOrdenarPor.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        cmbOrdenarPor.setForeground(new java.awt.Color(108, 117, 125));
        cmbOrdenarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuentas por Pagar", "Cuentas por Cobrar" }));
        cmbOrdenarPor.setBorder(null);
        jPanel2.add(cmbOrdenarPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 200, 30));

        jLabel16.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(33, 37, 41));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Ordenar Por");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 200, 20));

        txtBuscar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel2.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 160, 30));

        jLabel14.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(33, 37, 41));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Tipo de Cuenta");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 200, 20));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(660, 480));

        tblClientes1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No.", "Tipo", "Información", "Teléfono"
            }
        ));
        jScrollPane2.setViewportView(tblClientes1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 830, 210));

        cmbOrdenarPor1.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        cmbOrdenarPor1.setForeground(new java.awt.Color(108, 117, 125));
        cmbOrdenarPor1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIT", "Nombre", "Apellido", "Tipo de Cliente" }));
        cmbOrdenarPor1.setBorder(null);
        jPanel2.add(cmbOrdenarPor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 200, 30));

        jLabel19.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(33, 37, 41));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Número de Cuenta");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 140, 20));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(660, 480));

        tblMovCuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No. Documento", "No. Cuenta", "Banco", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMovCuentas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tblMovCuentas);
        if (tblMovCuentas.getColumnModel().getColumnCount() > 0) {
            tblMovCuentas.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 610, 300));

        jLabel5.setFont(new java.awt.Font("Skoda Pro", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(108, 117, 125));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Movimientos");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 880, 40));

        txtBuscar1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel2.add(txtBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 220, 30));

        jLabel20.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(33, 37, 41));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Buscar");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 200, 20));

        jLabel26.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(33, 37, 41));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Número de Documento");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 170, 20));

        txtBuscar2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel2.add(txtBuscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 160, 30));

        jLabel27.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(33, 37, 41));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setText("Banco");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 140, 20));

        txtBuscar3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel2.add(txtBuscar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 160, 30));

        jLabel28.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(33, 37, 41));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel28.setText("Fecha limite");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 170, 20));

        txtBuscar4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel2.add(txtBuscar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 160, 30));

        txtBuscar5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel2.add(txtBuscar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 160, 30));

        jLabel29.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(33, 37, 41));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setText("Valor total");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 170, 20));

        panelFondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 870, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnBuscar;
    private javax.swing.JComboBox<String> cmbOrdenarPor;
    private javax.swing.JComboBox<String> cmbOrdenarPor1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel lblBuscar;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JTable tblClientes1;
    private javax.swing.JTable tblMovCuentas;
    public javax.swing.JTextField txtBuscar;
    public javax.swing.JTextField txtBuscar1;
    public javax.swing.JTextField txtBuscar2;
    public javax.swing.JTextField txtBuscar3;
    public javax.swing.JTextField txtBuscar4;
    public javax.swing.JTextField txtBuscar5;
    // End of variables declaration//GEN-END:variables

    public void setControlador(ControladorMovimientoCuentas controlador) {
     
        this.btnBuscar.addMouseListener(controlador);
      
    }
    // En VistaClientes.java
// … class VistaClientes extends JPanel { …

    public javax.swing.JTable getTablaClientes() {
        return tblMovCuentas;   // <-- reemplaza por el nombre real de la tabla de clientes
    }

    public javax.swing.JTable getTablaContactos() {
        return tblClientes1;  // <-- reemplaza por el nombre real de la tabla de contactos
    }
 

  
}
