/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.umg.vistas;

import com.umg.controlador.ControladorProveedores;
import com.umg.controlador.ControladorRepresentantes;
import com.umg.modelo.ModeloProveedores;
import com.umg.modelo.ModeloRepresentates;

import javax.swing.*;

/**
 *
 * @author axels
 */
public class VistaRepresentantes extends javax.swing.JPanel {

    /**
     * Creates new form VistaClientes
     */
    public VistaRepresentantes() {
        initComponents();
        ModeloRepresentates modelo = new ModeloRepresentates(this);
        ControladorRepresentantes controlador = new ControladorRepresentantes(modelo);
        setControlador(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombreProveedor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDireccionFiscal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSegundoApellido = new javax.swing.JTextField();
        txtTelefonoProveedor = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtNitRepresentante = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPrimerNombre = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtSegundoNombre = new javax.swing.JTextField();
        txtApellidoCasada = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        panelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnBuscar = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lblBuscar = new javax.swing.JLabel();
        cmbOrdenarPor = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        lblLimpiar = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblNuevo = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblActualizar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblEliminar = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClientes1 = new javax.swing.JTable();
        cmbTipoContacto = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        txtInfoContacto = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        btnNuevo1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        lblNuevo1 = new javax.swing.JLabel();
        btnActualizar1 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        lblActualizar1 = new javax.swing.JLabel();
        btnEliminar1 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        lblEliminar1 = new javax.swing.JLabel();
        txtPrimerApellido = new javax.swing.JTextField();
        cmbProveedores = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(880, 720));
        setPreferredSize(new java.awt.Dimension(880, 720));

        panelFondo.setBackground(new java.awt.Color(245, 247, 250));
        panelFondo.setMinimumSize(new java.awt.Dimension(880, 720));
        panelFondo.setPreferredSize(new java.awt.Dimension(880, 720));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Skoda Pro", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(108, 117, 125));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Representantes");
        panelFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 40));

        jPanel2.setBackground(new java.awt.Color(245, 247, 250));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(33, 37, 41));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("NIT Proveedor");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 20));

        jLabel6.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(33, 37, 41));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Nombre");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 200, 20));

        txtNombreProveedor.setEditable(false);
        txtNombreProveedor.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel2.add(txtNombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 200, 30));

        jLabel7.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(33, 37, 41));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Dirección Fiscal");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 200, 20));

        txtDireccionFiscal.setEditable(false);
        txtDireccionFiscal.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel2.add(txtDireccionFiscal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 200, 30));

        jLabel10.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(33, 37, 41));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Segundo Apellido");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 200, 20));

        txtSegundoApellido.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel2.add(txtSegundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 200, 30));

        txtTelefonoProveedor.setEditable(false);
        txtTelefonoProveedor.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel2.add(txtTelefonoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 200, 30));

        jLabel19.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(33, 37, 41));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Teléfono");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 200, 20));

        txtNitRepresentante.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel2.add(txtNitRepresentante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 200, 30));

        jLabel8.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(33, 37, 41));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("NIT Representante");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 200, 20));

        jLabel9.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(33, 37, 41));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Primer Nombre");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 200, 20));

        txtPrimerNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel2.add(txtPrimerNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 200, 30));

        jLabel20.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(33, 37, 41));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Segundo Nombre");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 200, 20));

        txtSegundoNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel2.add(txtSegundoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 200, 30));

        txtApellidoCasada.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel2.add(txtApellidoCasada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 200, 30));

        jLabel11.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(33, 37, 41));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Apellido de Casada");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 200, 20));

        panelTabla.setBackground(new java.awt.Color(245, 247, 250));
        panelTabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(660, 480));

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NIT Proveedor", "Nombre Proveedor", "NIT Representante", "Nombre Representante"
            }
        ));
        jScrollPane1.setViewportView(tblClientes);

        panelTabla.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 260));

        jPanel2.add(panelTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 610, -1));

        btnBuscar.setBackground(new java.awt.Color(245, 247, 250));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Buscar");
        btnBuscar.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        lblBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBoton1.png"))); // NOI18N
        btnBuscar.add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, -1, -1));

        cmbOrdenarPor.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        cmbOrdenarPor.setForeground(new java.awt.Color(108, 117, 125));
        cmbOrdenarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIT Proveedor", "Nombre Proveedor", "NIT Representante", "Nombre Representante" }));
        cmbOrdenarPor.setBorder(null);
        jPanel2.add(cmbOrdenarPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 200, 30));

        jLabel16.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(33, 37, 41));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Ordenar Por");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 200, 20));

        txtBuscar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel2.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 220, 30));

        jLabel14.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(33, 37, 41));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Buscar");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 200, 20));

        btnLimpiar.setBackground(new java.awt.Color(245, 247, 250));
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Limpiar");
        btnLimpiar.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        lblLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBoton1.png"))); // NOI18N
        btnLimpiar.add(lblLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel2.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 100, 30));

        btnNuevo.setBackground(new java.awt.Color(245, 247, 250));
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nuevo");
        btnNuevo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        lblNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBoton1.png"))); // NOI18N
        btnNuevo.add(lblNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel2.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        btnActualizar.setBackground(new java.awt.Color(245, 247, 250));
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Actualizar");
        btnActualizar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        lblActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBoton1.png"))); // NOI18N
        btnActualizar.add(lblActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, 30));

        btnEliminar.setBackground(new java.awt.Color(245, 247, 250));
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Eliminar");
        btnEliminar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        lblEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBoton1.png"))); // NOI18N
        btnEliminar.add(lblEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, -1));

        jLabel13.setFont(new java.awt.Font("Skoda Pro", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(108, 117, 125));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Contacto Prepresentante");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 220, -1));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(660, 480));

        tblClientes1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No.", "Tipo", "Información"
            }
        ));
        jScrollPane2.setViewportView(tblClientes1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 380, 170));

        cmbTipoContacto.setForeground(new java.awt.Color(108, 117, 125));
        cmbTipoContacto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTipoContacto.setBorder(null);
        jPanel2.add(cmbTipoContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 200, 30));

        jLabel17.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(33, 37, 41));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Tipo de Contacto");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 200, 20));

        txtInfoContacto.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel2.add(txtInfoContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, 200, 30));

        jLabel21.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(33, 37, 41));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Información");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 200, 20));

        btnNuevo1.setBackground(new java.awt.Color(245, 247, 250));
        btnNuevo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Nuevo C.");
        btnNuevo1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        lblNuevo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBoton1.png"))); // NOI18N
        btnNuevo1.add(lblNuevo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel2.add(btnNuevo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 610, -1, -1));

        btnActualizar1.setBackground(new java.awt.Color(245, 247, 250));
        btnActualizar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Actualizar C.");
        btnActualizar1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        lblActualizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBoton1.png"))); // NOI18N
        btnActualizar1.add(lblActualizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel2.add(btnActualizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 610, -1, 30));

        btnEliminar1.setBackground(new java.awt.Color(245, 247, 250));
        btnEliminar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Eliminar C.");
        btnEliminar1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        lblEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBoton1.png"))); // NOI18N
        btnEliminar1.add(lblEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel2.add(btnEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 610, -1, -1));

        txtPrimerApellido.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel2.add(txtPrimerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 200, 30));

        cmbProveedores.setForeground(new java.awt.Color(108, 117, 125));
        cmbProveedores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbProveedores.setBorder(null);
        jPanel2.add(cmbProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 200, 30));

        jLabel26.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(33, 37, 41));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Primer Apellido");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 200, 20));

        panelFondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 870, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnActualizar;
    public javax.swing.JPanel btnActualizar1;
    public javax.swing.JPanel btnBuscar;
    public javax.swing.JPanel btnEliminar;
    public javax.swing.JPanel btnEliminar1;
    public javax.swing.JPanel btnLimpiar;
    public javax.swing.JPanel btnNuevo;
    public javax.swing.JPanel btnNuevo1;
    private javax.swing.JComboBox<String> cmbOrdenarPor;
    public javax.swing.JComboBox<String> cmbProveedores;
    private javax.swing.JComboBox<String> cmbTipoContacto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel lblActualizar;
    public javax.swing.JLabel lblActualizar1;
    public javax.swing.JLabel lblBuscar;
    public javax.swing.JLabel lblEliminar;
    public javax.swing.JLabel lblEliminar1;
    public javax.swing.JLabel lblLimpiar;
    public javax.swing.JLabel lblNuevo;
    public javax.swing.JLabel lblNuevo1;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JTable tblClientes;
    public javax.swing.JTable tblClientes1;
    public javax.swing.JTextField txtApellidoCasada;
    public javax.swing.JTextField txtBuscar;
    public javax.swing.JTextField txtDireccionFiscal;
    public javax.swing.JTextField txtInfoContacto;
    public javax.swing.JTextField txtNitRepresentante;
    public javax.swing.JTextField txtNombreProveedor;
    public javax.swing.JTextField txtPrimerApellido;
    public javax.swing.JTextField txtPrimerNombre;
    public javax.swing.JTextField txtSegundoApellido;
    public javax.swing.JTextField txtSegundoNombre;
    public javax.swing.JTextField txtTelefonoProveedor;
    // End of variables declaration//GEN-END:variables

    public void setControlador(ControladorRepresentantes controlador) {
        this.btnActualizar.addMouseListener(controlador);
        this.btnEliminar.addMouseListener(controlador);
        this.btnNuevo.addMouseListener(controlador);
        this.btnBuscar.addMouseListener(controlador);
        this.btnLimpiar.addMouseListener(controlador);
    }
    public javax.swing.JTable getTablaContactos() {
        return tblClientes1;
    }

    public javax.swing.JComboBox<String> getCmbTipoContacto() {
        return cmbTipoContacto;
    }

    public javax.swing.JComboBox<String> getCmbProveedores() {
        return cmbProveedores;
    }
    public javax.swing.JTable getTablaClientes() {
        return tblClientes;   // tabla de representantes
    }

}
