/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.umg.vistas;

import com.umg.controlador.ControladorMenuClientes;
import com.umg.controlador.ControladorMenuCuentas;
import com.umg.controlador.ControladorMenuInventario;
import com.umg.modelo.ModeloMenuClientes;
import com.umg.modelo.ModeloMenuCuentas;
import com.umg.modelo.ModeloMenuInventario;

/**
 *
 * @author axels
 */
public class VistaMenuInventario extends javax.swing.JPanel {

    /**
     * Creates new form VistaMenuCuentas
     */
    public VistaMenuInventario() {
        initComponents();
        ModeloMenuInventario modelo = new ModeloMenuInventario(this);
        ControladorMenuInventario controlador = new ControladorMenuInventario(modelo);
        setControlador(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMovimientoStock = new javax.swing.JPanel();
        lblIconoMovimientoStock = new javax.swing.JLabel();
        lblMovimientoStock = new javax.swing.JLabel();
        lblMovimientoStockSeleccionado = new javax.swing.JLabel();
        btnAjustesManuales = new javax.swing.JPanel();
        lblIconoAjustesManuales = new javax.swing.JLabel();
        lblAjustesManuales = new javax.swing.JLabel();
        lblAjustesManualesSeleccionado = new javax.swing.JLabel();
        contenedor = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1080, 720));

        panelFondo.setBackground(new java.awt.Color(245, 247, 250));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenu.setBackground(new java.awt.Color(245, 247, 250));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Skoda Pro", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(108, 117, 125));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inventario");
        panelMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        btnMovimientoStock.setBackground(new java.awt.Color(245, 247, 250));
        btnMovimientoStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMovimientoStock.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoMovimientoStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoInicio.png"))); // NOI18N
        btnMovimientoStock.add(lblIconoMovimientoStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblMovimientoStock.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        lblMovimientoStock.setForeground(new java.awt.Color(51, 51, 51));
        lblMovimientoStock.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMovimientoStock.setText("Mov. de Stock");
        btnMovimientoStock.add(lblMovimientoStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblMovimientoStockSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnMovimientoStock.add(lblMovimientoStockSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnMovimientoStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 180, 40));

        btnAjustesManuales.setBackground(new java.awt.Color(245, 247, 250));
        btnAjustesManuales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAjustesManuales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoAjustesManuales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoClientes.png"))); // NOI18N
        btnAjustesManuales.add(lblIconoAjustesManuales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblAjustesManuales.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        lblAjustesManuales.setForeground(new java.awt.Color(51, 51, 51));
        lblAjustesManuales.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAjustesManuales.setText("Ajustes Manuales");
        btnAjustesManuales.add(lblAjustesManuales, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblAjustesManualesSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnAjustesManuales.add(lblAjustesManualesSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnAjustesManuales, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 180, 40));

        panelFondo.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 720));

        contenedor.setBackground(new java.awt.Color(245, 247, 250));
        contenedor.setLayout(new java.awt.BorderLayout());
        panelFondo.add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 880, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnAjustesManuales;
    public javax.swing.JPanel btnMovimientoStock;
    public javax.swing.JPanel contenedor;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lblAjustesManuales;
    public javax.swing.JLabel lblAjustesManualesSeleccionado;
    public javax.swing.JLabel lblIconoAjustesManuales;
    public javax.swing.JLabel lblIconoMovimientoStock;
    public javax.swing.JLabel lblMovimientoStock;
    public javax.swing.JLabel lblMovimientoStockSeleccionado;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables

    public void setControlador(ControladorMenuInventario controlador) {
        this.btnMovimientoStock.addMouseListener(controlador);
        this.btnAjustesManuales.addMouseListener(controlador);
    }
}
