/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.umg.vistas;

import com.umg.controlador.ControladorMenuClientes;
import com.umg.controlador.ControladorMenuCuentas;
import com.umg.modelo.ModeloMenuClientes;
import com.umg.modelo.ModeloMenuCuentas;

/**
 *
 * @author axels
 */
public class VistaMenuClientes extends javax.swing.JPanel {

    /**
     * Creates new form VistaMenuCuentas
     */
    public VistaMenuClientes() {
        initComponents();
        ModeloMenuClientes modelo = new ModeloMenuClientes(this);
        ControladorMenuClientes controlador = new ControladorMenuClientes(modelo);
        setControlador(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnGestionClientes = new javax.swing.JPanel();
        lblIconoGestionClientes = new javax.swing.JLabel();
        lblGestionClientes = new javax.swing.JLabel();
        lblGestionClientesSeleccionado = new javax.swing.JLabel();
        btnTiposDeCliente = new javax.swing.JPanel();
        lblIconoTiposDeCliente = new javax.swing.JLabel();
        lblTiposDeCliente = new javax.swing.JLabel();
        lblTiposDeClienteSeleccionado = new javax.swing.JLabel();
        contenedor = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1080, 720));

        panelFondo.setBackground(new java.awt.Color(245, 247, 250));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenu.setBackground(new java.awt.Color(245, 247, 250));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Skoda Pro", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(108, 117, 125));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Clientes");
        panelMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        btnGestionClientes.setBackground(new java.awt.Color(245, 247, 250));
        btnGestionClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGestionClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoGestionClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoInicio.png"))); // NOI18N
        btnGestionClientes.add(lblIconoGestionClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblGestionClientes.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        lblGestionClientes.setForeground(new java.awt.Color(51, 51, 51));
        lblGestionClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGestionClientes.setText("Gestión de Clientes");
        btnGestionClientes.add(lblGestionClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblGestionClientesSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnGestionClientes.add(lblGestionClientesSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnGestionClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 180, 40));

        btnTiposDeCliente.setBackground(new java.awt.Color(245, 247, 250));
        btnTiposDeCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTiposDeCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoTiposDeCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoClientes.png"))); // NOI18N
        btnTiposDeCliente.add(lblIconoTiposDeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblTiposDeCliente.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        lblTiposDeCliente.setForeground(new java.awt.Color(51, 51, 51));
        lblTiposDeCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTiposDeCliente.setText("Tipos de Cliente");
        btnTiposDeCliente.add(lblTiposDeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblTiposDeClienteSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnTiposDeCliente.add(lblTiposDeClienteSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnTiposDeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 180, 40));

        panelFondo.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 720));

        contenedor.setBackground(new java.awt.Color(245, 247, 250));
        contenedor.setLayout(new java.awt.BorderLayout());
        panelFondo.add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 880, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnGestionClientes;
    public javax.swing.JPanel btnTiposDeCliente;
    public javax.swing.JPanel contenedor;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lblGestionClientes;
    public javax.swing.JLabel lblGestionClientesSeleccionado;
    public javax.swing.JLabel lblIconoGestionClientes;
    public javax.swing.JLabel lblIconoTiposDeCliente;
    public javax.swing.JLabel lblTiposDeCliente;
    public javax.swing.JLabel lblTiposDeClienteSeleccionado;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables

    public void setControlador(ControladorMenuClientes controlador) {
        this.btnGestionClientes.addMouseListener(controlador);
        this.btnTiposDeCliente.addMouseListener(controlador);
    }
}
