/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.umg.vistas;

import com.umg.controlador.ControladorCategoria;
import com.umg.controlador.ControladorReporteClientesYProductos;
import com.umg.controlador.ControladorReporteVentasYCompras;
import com.umg.modelo.ModeloCategoria;
import com.umg.modelo.ModeloReporteClientesYProductos;
import com.umg.modelo.ModeloReporteVentasYCompras;

/**
 *
 * @author axels
 */
public class VistaReporteClientesYProductos extends javax.swing.JPanel {

    /**
     * Creates new form VistaCuentasPorCobrar
     */
    public VistaReporteClientesYProductos() {
        initComponents();
        ModeloReporteClientesYProductos modelo = new ModeloReporteClientesYProductos(this);
        ControladorReporteClientesYProductos controlador = new ControladorReporteClientesYProductos(modelo);
        setControlador(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbTipoReporte = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReporte = new javax.swing.JTable();
        btnVerReporte = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        lblVerReporte = new javax.swing.JLabel();
        btnGenerarPDF = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblGenerarPDF = new javax.swing.JLabel();
        btnGenerarExcel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblGenerarExcel = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblLimpiar = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFechaFin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(880, 720));
        setPreferredSize(new java.awt.Dimension(880, 720));

        jPanel1.setBackground(new java.awt.Color(245, 247, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Skoda Pro", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(108, 117, 125));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reporte de Clientes y Productos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 40));

        cmbTipoReporte.setBackground(new java.awt.Color(255, 255, 255));
        cmbTipoReporte.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        cmbTipoReporte.setForeground(new java.awt.Color(108, 117, 125));
        cmbTipoReporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mejores clientes por monto", "Mejores clientes por facturas", "Productos más vendidos por cantidad", "Productos más vendidos por monto", "Producto con stock bajo" }));
        cmbTipoReporte.setBorder(null);
        jPanel1.add(cmbTipoReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 340, 30));

        jLabel16.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(33, 37, 41));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Tipo de Reporte");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 200, 20));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(660, 480));

        tblReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Reporte"
            }
        ));
        jScrollPane1.setViewportView(tblReporte);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 610, 560));

        btnVerReporte.setBackground(new java.awt.Color(245, 247, 250));
        btnVerReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerReporte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Ver Reporte");
        btnVerReporte.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        lblVerReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBoton1.png"))); // NOI18N
        btnVerReporte.add(lblVerReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel1.add(btnVerReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 100, 30));

        btnGenerarPDF.setBackground(new java.awt.Color(245, 247, 250));
        btnGenerarPDF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerarPDF.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Gen. PDF");
        btnGenerarPDF.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        lblGenerarPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBoton1.png"))); // NOI18N
        btnGenerarPDF.add(lblGenerarPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel1.add(btnGenerarPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        btnGenerarExcel.setBackground(new java.awt.Color(245, 247, 250));
        btnGenerarExcel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerarExcel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gen. Excel");
        btnGenerarExcel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        lblGenerarExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBoton1.png"))); // NOI18N
        btnGenerarExcel.add(lblGenerarExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel1.add(btnGenerarExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, -1, 30));

        btnLimpiar.setBackground(new java.awt.Color(245, 247, 250));
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Limpiar");
        btnLimpiar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        lblLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBoton1.png"))); // NOI18N
        btnLimpiar.add(lblLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, -1, -1));

        txtFechaInicio.setBackground(new java.awt.Color(255, 255, 255));
        txtFechaInicio.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel1.add(txtFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 200, 30));

        jLabel6.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(33, 37, 41));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Fecha de Inicio");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 200, 20));

        txtFechaFin.setBackground(new java.awt.Color(255, 255, 255));
        txtFechaFin.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel1.add(txtFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 200, 30));

        jLabel5.setFont(new java.awt.Font("Skoda Pro", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(33, 37, 41));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Fecha de Fin");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 200, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnGenerarExcel;
    public javax.swing.JPanel btnGenerarPDF;
    public javax.swing.JPanel btnLimpiar;
    public javax.swing.JPanel btnVerReporte;
    public javax.swing.JComboBox<String> cmbTipoReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblGenerarExcel;
    public javax.swing.JLabel lblGenerarPDF;
    public javax.swing.JLabel lblLimpiar;
    public javax.swing.JLabel lblVerReporte;
    public javax.swing.JTable tblReporte;
    public javax.swing.JTextField txtFechaFin;
    public javax.swing.JTextField txtFechaInicio;
    // End of variables declaration//GEN-END:variables
    public void setControlador(ControladorReporteClientesYProductos controlador) {
        this.btnGenerarExcel.addMouseListener(controlador);
        this.btnLimpiar.addMouseListener(controlador);
        this.btnGenerarPDF.addMouseListener(controlador);
        this.btnVerReporte.addMouseListener(controlador);
    }
}
