/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.umg.vistas;

import com.umg.controlador.ControladorMenuConfiguracion;
import com.umg.controlador.ControladorMenuProductos;
import com.umg.modelo.ModeloMenuConfiguracion;
import com.umg.modelo.ModeloMenuProductos;

/**
 *
 * @author axels
 */
public class VistaMenuProductos extends javax.swing.JPanel {

    /**
     * Creates new form VistaMenuCuentas
     */
    public VistaMenuProductos() {
        initComponents();
        ModeloMenuProductos modelo = new  ModeloMenuProductos(this);
        ControladorMenuProductos controlador = new ControladorMenuProductos(modelo);
        setControlador(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        contenedor = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnGestionProductos = new javax.swing.JPanel();
        lblIconoGestionProductos = new javax.swing.JLabel();
        lblGestionProductos = new javax.swing.JLabel();
        lblGestionProductosSeleccionado = new javax.swing.JLabel();
        btnPrecios = new javax.swing.JPanel();
        lblIconoPrecios = new javax.swing.JLabel();
        lblPrecios = new javax.swing.JLabel();
        lblPreciosSeleccionado = new javax.swing.JLabel();
        btnAsigImpuestos = new javax.swing.JPanel();
        lblIconoAsigImpuestos = new javax.swing.JLabel();
        lblAsigImpuestos = new javax.swing.JLabel();
        lblAsigImpuestosSeleccionado = new javax.swing.JLabel();
        btnAsigDescuentos = new javax.swing.JPanel();
        lblIconoAsigDescuentos = new javax.swing.JLabel();
        lblAsigDescuentos = new javax.swing.JLabel();
        lblAsigDescuentosSeleccionado = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1080, 720));

        panelFondo.setBackground(new java.awt.Color(245, 247, 250));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenedor.setBackground(new java.awt.Color(245, 247, 250));
        contenedor.setLayout(new java.awt.BorderLayout());
        panelFondo.add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 880, 720));

        panelMenu.setBackground(new java.awt.Color(245, 247, 250));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Skoda Pro", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(108, 117, 125));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Productos");
        panelMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        btnGestionProductos.setBackground(new java.awt.Color(245, 247, 250));
        btnGestionProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGestionProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoGestionProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoInicio.png"))); // NOI18N
        btnGestionProductos.add(lblIconoGestionProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblGestionProductos.setFont(new java.awt.Font("Skoda Pro", 0, 12)); // NOI18N
        lblGestionProductos.setForeground(new java.awt.Color(51, 51, 51));
        lblGestionProductos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGestionProductos.setText("Gestión de Productos");
        btnGestionProductos.add(lblGestionProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblGestionProductosSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnGestionProductos.add(lblGestionProductosSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnGestionProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 180, 40));

        btnPrecios.setBackground(new java.awt.Color(245, 247, 250));
        btnPrecios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrecios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoPrecios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoClientes.png"))); // NOI18N
        btnPrecios.add(lblIconoPrecios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblPrecios.setFont(new java.awt.Font("Skoda Pro", 0, 14)); // NOI18N
        lblPrecios.setForeground(new java.awt.Color(51, 51, 51));
        lblPrecios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPrecios.setText("Precios");
        btnPrecios.add(lblPrecios, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblPreciosSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnPrecios.add(lblPreciosSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnPrecios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 180, 40));

        btnAsigImpuestos.setBackground(new java.awt.Color(245, 247, 250));
        btnAsigImpuestos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAsigImpuestos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoAsigImpuestos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoVentas.png"))); // NOI18N
        btnAsigImpuestos.add(lblIconoAsigImpuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblAsigImpuestos.setFont(new java.awt.Font("Skoda Pro", 0, 11)); // NOI18N
        lblAsigImpuestos.setForeground(new java.awt.Color(51, 51, 51));
        lblAsigImpuestos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAsigImpuestos.setText("Asignación de Impuestos");
        btnAsigImpuestos.add(lblAsigImpuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblAsigImpuestosSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnAsigImpuestos.add(lblAsigImpuestosSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnAsigImpuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 180, 40));

        btnAsigDescuentos.setBackground(new java.awt.Color(245, 247, 250));
        btnAsigDescuentos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAsigDescuentos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoAsigDescuentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoProductos.png"))); // NOI18N
        btnAsigDescuentos.add(lblIconoAsigDescuentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblAsigDescuentos.setFont(new java.awt.Font("Skoda Pro", 0, 11)); // NOI18N
        lblAsigDescuentos.setForeground(new java.awt.Color(51, 51, 51));
        lblAsigDescuentos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAsigDescuentos.setText("Asignación de Descuentos");
        btnAsigDescuentos.add(lblAsigDescuentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 40));

        lblAsigDescuentosSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/iconos/IconoBotonesSeleccionados.png"))); // NOI18N
        btnAsigDescuentos.add(lblAsigDescuentosSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelMenu.add(btnAsigDescuentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 180, 40));

        panelFondo.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnAsigDescuentos;
    public javax.swing.JPanel btnAsigImpuestos;
    public javax.swing.JPanel btnGestionProductos;
    public javax.swing.JPanel btnPrecios;
    public javax.swing.JPanel contenedor;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lblAsigDescuentos;
    public javax.swing.JLabel lblAsigDescuentosSeleccionado;
    public javax.swing.JLabel lblAsigImpuestos;
    public javax.swing.JLabel lblAsigImpuestosSeleccionado;
    public javax.swing.JLabel lblGestionProductos;
    public javax.swing.JLabel lblGestionProductosSeleccionado;
    public javax.swing.JLabel lblIconoAsigDescuentos;
    public javax.swing.JLabel lblIconoAsigImpuestos;
    public javax.swing.JLabel lblIconoGestionProductos;
    public javax.swing.JLabel lblIconoPrecios;
    public javax.swing.JLabel lblPrecios;
    public javax.swing.JLabel lblPreciosSeleccionado;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables

    public void setControlador(ControladorMenuProductos controlador) {
        this.btnGestionProductos.addMouseListener(controlador);
        this.btnPrecios.addMouseListener(controlador);
        this.btnAsigImpuestos.addMouseListener(controlador);
        this.btnAsigDescuentos.addMouseListener(controlador);
    }
}
